/* ============================================================
   MON CARNET FRANÇAIS — Datos del curso (Nivel A1)
   ============================================================ */

const LESSONS = [
  {
    id: 1,
    title: "Bonjour !",
    subtitle: "Saludos, despedidas y presentaciones",
    icon: "👋",
    vocab: [
      { fr: "Bonjour", es: "Hola / Buenos días", emoji: "☀️" },
      { fr: "Bonsoir", es: "Buenas tardes/noches", emoji: "🌆" },
      { fr: "Salut", es: "Hola (informal)", emoji: "🙋" },
      { fr: "Au revoir", es: "Adiós", emoji: "👋" },
      { fr: "Merci", es: "Gracias", emoji: "🙏" },
      { fr: "S'il vous plaît", es: "Por favor", emoji: "🥺" },
      { fr: "Comment tu t'appelles ?", es: "¿Cómo te llamas?", emoji: "❓" },
      { fr: "Je m'appelle...", es: "Me llamo...", emoji: "🧑" },
    ],
    grammar: {
      title: "Presentarse en francés",
      text: "Para presentarte usas 'Je m'appelle' + tu nombre. Para saludar formalmente usa 'Bonjour', y con amigos 'Salut'. Un truco de pronunciación: la 'R' francesa suena en la garganta (como al hacer gárgaras) y muchas letras finales NO se pronuncian, por ejemplo 'Bonjour' termina en un sonido suave, no en una 'r' fuerte.",
      examples: [
        { fr: "— Bonjour ! Je m'appelle Marie.", es: "— Hola, me llamo Marie." },
        { fr: "— Salut, comment ça va ?", es: "— Hola, ¿cómo estás?" },
        { fr: "— Ça va bien, merci !", es: "— Estoy bien, ¡gracias!" },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'Gracias' en francés?", options: ["Bonjour", "Merci", "Salut", "Pardon"], answer: 1 },
      { type: "fill", question: "— ___ ! Je m'appelle Paul. (Hola)", answer: "Bonjour", hint: "Saludo formal para empezar el día" },
      { type: "match", pairs: [
        { fr: "Au revoir", es: "Adiós" },
        { fr: "Merci", es: "Gracias" },
        { fr: "Salut", es: "Hola (informal)" },
        { fr: "S'il vous plaît", es: "Por favor" },
      ]},
    ],
  },
  {
    id: 2,
    title: "Les nombres",
    subtitle: "Los números del 0 al 20",
    icon: "🔢",
    vocab: [
      { fr: "zéro", es: "0", emoji: "0️⃣" },
      { fr: "un", es: "1", emoji: "1️⃣" },
      { fr: "deux", es: "2", emoji: "2️⃣" },
      { fr: "trois", es: "3", emoji: "3️⃣" },
      { fr: "quatre", es: "4", emoji: "4️⃣" },
      { fr: "cinq", es: "5", emoji: "5️⃣" },
      { fr: "dix", es: "10", emoji: "🔟" },
      { fr: "quinze", es: "15", emoji: "🔢" },
      { fr: "vingt", es: "20", emoji: "🔢" },
    ],
    grammar: {
      title: "Contar del 0 al 20",
      text: "Del 1 al 16 cada número tiene una palabra única. A partir del 17 se combinan: 'dix-sept' (10+7), 'dix-huit' (10+8), 'dix-neuf' (10+9). Fíjate que 'six' y 'dix' cambian un poco su pronunciación según lo que sigue.",
      examples: [
        { fr: "onze, douze, treize, quatorze", es: "once, doce, trece, catorce" },
        { fr: "dix-sept, dix-huit, dix-neuf, vingt", es: "diecisiete, dieciocho, diecinueve, veinte" },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice '7' en francés?", options: ["sept", "neuf", "six", "huit"], answer: 0 },
      { type: "fill", question: "9 + 1 = ___ (en francés, escribe 'dix')", answer: "dix", hint: "Es el número 10" },
      { type: "match", pairs: [
        { fr: "cinq", es: "5" },
        { fr: "huit", es: "8" },
        { fr: "douze", es: "12" },
        { fr: "vingt", es: "20" },
      ]},
    ],
  },
  {
    id: 3,
    title: "Nombres et âge",
    subtitle: "Números del 21 al 100 y la edad",
    icon: "🎂",
    vocab: [
      { fr: "vingt et un", es: "21", emoji: "🔢" },
      { fr: "trente", es: "30", emoji: "🔢" },
      { fr: "quarante", es: "40", emoji: "🔢" },
      { fr: "cinquante", es: "50", emoji: "🔢" },
      { fr: "soixante", es: "60", emoji: "🔢" },
      { fr: "cent", es: "100", emoji: "💯" },
      { fr: "l'âge", es: "la edad", emoji: "🎂" },
      { fr: "J'ai ... ans", es: "Tengo ... años", emoji: "🎉" },
    ],
    grammar: {
      title: "Decenas y la edad",
      text: "Las decenas siguen un patrón: trente (30), quarante (40), cinquante (50), soixante (60)... En francés de Francia, después del 69 se cuenta raro: 'soixante-dix' (70 = 60+10), 'quatre-vingts' (80 = 4×20), 'quatre-vingt-dix' (90 = 4×20+10). Para decir la edad NO se usa 'être' sino 'avoir': 'J'ai vingt ans' (Tengo veinte años), literalmente 'Tengo veinte años' usa el verbo 'tener'.",
      examples: [
        { fr: "J'ai vingt-cinq ans.", es: "Tengo veinticinco años." },
        { fr: "Elle a trente ans.", es: "Ella tiene treinta años." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Qué verbo se usa para decir la edad en francés?", options: ["être", "avoir", "aller", "faire"], answer: 1 },
      { type: "fill", question: "J'ai vingt ___ (años)", answer: "ans", hint: "Plural de 'an'" },
      { type: "match", pairs: [
        { fr: "trente", es: "30" },
        { fr: "cinquante", es: "50" },
        { fr: "cent", es: "100" },
        { fr: "soixante", es: "60" },
      ]},
    ],
  },
  {
    id: 4,
    title: "Être",
    subtitle: "El verbo ser / estar",
    icon: "🧭",
    vocab: [
      { fr: "je suis", es: "yo soy/estoy", emoji: "🧍" },
      { fr: "tu es", es: "tú eres/estás", emoji: "🧍‍♂️" },
      { fr: "il/elle est", es: "él/ella es/está", emoji: "🧑" },
      { fr: "nous sommes", es: "nosotros somos/estamos", emoji: "👥" },
      { fr: "vous êtes", es: "ustedes son/están", emoji: "👥" },
      { fr: "ils/elles sont", es: "ellos/ellas son/están", emoji: "👥" },
    ],
    grammar: {
      title: "Conjugación de 'être' (ser/estar)",
      text: "'Être' es uno de los verbos más importantes y es irregular, así que hay que memorizarlo. Se usa para describir identidad, nacionalidad, profesión y estados: 'Je suis étudiant' (Soy estudiante), 'Il est fatigué' (Está cansado).",
      examples: [
        { fr: "Je suis mexicain(e).", es: "Soy mexicano(a)." },
        { fr: "Nous sommes contents.", es: "Estamos contentos." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se conjuga 'être' con 'nous'?", options: ["sommes", "êtes", "sont", "suis"], answer: 0 },
      { type: "fill", question: "Tu ___ français ? (eres)", answer: "es", hint: "Segunda persona singular de être" },
      { type: "match", pairs: [
        { fr: "je suis", es: "yo soy" },
        { fr: "vous êtes", es: "ustedes son" },
        { fr: "ils sont", es: "ellos son" },
        { fr: "elle est", es: "ella es" },
      ]},
    ],
  },
  {
    id: 5,
    title: "Avoir",
    subtitle: "El verbo tener",
    icon: "🎒",
    vocab: [
      { fr: "j'ai", es: "yo tengo", emoji: "🎒" },
      { fr: "tu as", es: "tú tienes", emoji: "🎒" },
      { fr: "il/elle a", es: "él/ella tiene", emoji: "🎒" },
      { fr: "nous avons", es: "nosotros tenemos", emoji: "🎒" },
      { fr: "vous avez", es: "ustedes tienen", emoji: "🎒" },
      { fr: "ils/elles ont", es: "ellos/ellas tienen", emoji: "🎒" },
    ],
    grammar: {
      title: "Conjugación de 'avoir' (tener)",
      text: "'Avoir' también es irregular y se usa muchísimo, incluso en expresiones donde el español usa 'ser/estar': 'avoir faim' (tener hambre = estar hambriento), 'avoir soif' (tener sed), 'avoir froid/chaud' (tener frío/calor).",
      examples: [
        { fr: "J'ai faim.", es: "Tengo hambre." },
        { fr: "Ils ont un chat.", es: "Ellos tienen un gato." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'ellos tienen'?", options: ["ils sont", "ils ont", "ils avons", "ils a"], answer: 1 },
      { type: "fill", question: "Nous ___ faim. (tenemos)", answer: "avons", hint: "Primera persona plural de avoir" },
      { type: "match", pairs: [
        { fr: "j'ai", es: "yo tengo" },
        { fr: "tu as", es: "tú tienes" },
        { fr: "vous avez", es: "ustedes tienen" },
        { fr: "elle a", es: "ella tiene" },
      ]},
    ],
  },
  {
    id: 6,
    title: "Les articles",
    subtitle: "Artículos definidos e indefinidos",
    icon: "🪧",
    vocab: [
      { fr: "le", es: "el (masc.)", emoji: "🔵" },
      { fr: "la", es: "la (fem.)", emoji: "🔴" },
      { fr: "les", es: "los/las (plural)", emoji: "🟢" },
      { fr: "un", es: "un (masc.)", emoji: "🔵" },
      { fr: "une", es: "una (fem.)", emoji: "🔴" },
      { fr: "des", es: "unos/unas", emoji: "🟢" },
    ],
    grammar: {
      title: "Género y artículos",
      text: "En francés todos los sustantivos tienen género (masculino o femenino), y no siempre coincide con el español. Usa 'le/un' para masculino, 'la/une' para femenino y 'les/des' para plural. Antes de vocal o 'h muda', 'le' y 'la' se acortan a l' : l'ami, l'école.",
      examples: [
        { fr: "le garçon / la fille", es: "el niño / la niña" },
        { fr: "un livre / une pomme", es: "un libro / una manzana" },
        { fr: "l'école (fem.)", es: "la escuela" },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Qué artículo usarías antes de 'école' (escuela)?", options: ["le", "la", "l'", "les"], answer: 2 },
      { type: "fill", question: "___ pomme est rouge. (La manzana es roja)", answer: "La", hint: "Artículo femenino singular" },
      { type: "match", pairs: [
        { fr: "le", es: "el" },
        { fr: "une", es: "una" },
        { fr: "les", es: "los/las" },
        { fr: "des", es: "unos/unas" },
      ]},
    ],
  },
  {
    id: 7,
    title: "Le pluriel",
    subtitle: "El plural de los sustantivos",
    icon: "➕",
    vocab: [
      { fr: "un chat → des chats", es: "un gato → gatos", emoji: "🐱" },
      { fr: "un livre → des livres", es: "un libro → libros", emoji: "📚" },
      { fr: "un animal → des animaux", es: "un animal → animales", emoji: "🐾" },
      { fr: "un cheval → des chevaux", es: "un caballo → caballos", emoji: "🐴" },
      { fr: "un jeu → des jeux", es: "un juego → juegos", emoji: "🎮" },
    ],
    grammar: {
      title: "Formar el plural",
      text: "Casi siempre se añade una 's' al final (que no se pronuncia): chat → chats. Las palabras que terminan en '-al' cambian a '-aux': animal → animaux, cheval → chevaux. Las que terminan en '-eau' o '-eu' añaden 'x': jeu → jeux.",
      examples: [
        { fr: "les enfants jouent avec les chats.", es: "los niños juegan con los gatos." },
        { fr: "des chevaux magnifiques", es: "caballos magníficos" },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cuál es el plural de 'un animal'?", options: ["des animals", "des animaux", "des animales", "des animal"], answer: 1 },
      { type: "fill", question: "un chat → des ___", answer: "chats", hint: "Regla general: añade 's'" },
      { type: "match", pairs: [
        { fr: "un jeu", es: "un juego" },
        { fr: "des jeux", es: "juegos" },
        { fr: "un cheval", es: "un caballo" },
        { fr: "des chevaux", es: "caballos" },
      ]},
    ],
  },
  {
    id: 8,
    title: "Les couleurs",
    subtitle: "Los colores",
    icon: "🎨",
    vocab: [
      { fr: "rouge", es: "rojo", emoji: "🔴" },
      { fr: "bleu", es: "azul", emoji: "🔵" },
      { fr: "vert", es: "verde", emoji: "🟢" },
      { fr: "jaune", es: "amarillo", emoji: "🟡" },
      { fr: "noir", es: "negro", emoji: "⚫" },
      { fr: "blanc", es: "blanco", emoji: "⚪" },
      { fr: "violet", es: "morado", emoji: "🟣" },
      { fr: "orange", es: "naranja", emoji: "🟠" },
    ],
    grammar: {
      title: "Los colores concuerdan en género",
      text: "Los colores son adjetivos y cambian según el género del sustantivo: 'un pull bleu' (un suéter azul) pero 'une robe bleue' (un vestido azul, con 'e' extra). Colores como 'orange' y 'violet' tienen sus propias reglas especiales.",
      examples: [
        { fr: "Le ciel est bleu.", es: "El cielo es azul." },
        { fr: "La voiture est rouge.", es: "El coche es rojo." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'verde' en francés?", options: ["vert", "violet", "jaune", "noir"], answer: 0 },
      { type: "fill", question: "Le soleil est ___. (amarillo)", answer: "jaune", hint: "Color del sol" },
      { type: "match", pairs: [
        { fr: "rouge", es: "rojo" },
        { fr: "blanc", es: "blanco" },
        { fr: "noir", es: "negro" },
        { fr: "violet", es: "morado" },
      ]},
    ],
  },
  {
    id: 9,
    title: "La famille",
    subtitle: "La familia",
    icon: "👨‍👩‍👧‍👦",
    vocab: [
      { fr: "la mère", es: "la madre", emoji: "👩" },
      { fr: "le père", es: "el padre", emoji: "👨" },
      { fr: "le frère", es: "el hermano", emoji: "👦" },
      { fr: "la sœur", es: "la hermana", emoji: "👧" },
      { fr: "les parents", es: "los padres", emoji: "👨‍👩‍👦" },
      { fr: "le fils", es: "el hijo", emoji: "👦" },
      { fr: "la fille", es: "la hija", emoji: "👧" },
      { fr: "les grands-parents", es: "los abuelos", emoji: "👴👵" },
    ],
    grammar: {
      title: "Adjetivos posesivos con la familia",
      text: "Para hablar de tu familia usa 'mon/ma/mes' (mi/mis): 'mon père' (mi padre, masc.), 'ma mère' (mi madre, fem.), 'mes parents' (mis padres, plural). Antes de vocal, 'ma' se convierte en 'mon': mon amie.",
      examples: [
        { fr: "Voici mon père et ma sœur.", es: "Aquí están mi padre y mi hermana." },
        { fr: "Mes grands-parents habitent à Paris.", es: "Mis abuelos viven en París." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'hermana' en francés?", options: ["le frère", "la sœur", "la fille", "la mère"], answer: 1 },
      { type: "fill", question: "Voici ___ mère. (mi, femenino)", answer: "ma", hint: "Posesivo femenino de 1ra persona" },
      { type: "match", pairs: [
        { fr: "le père", es: "el padre" },
        { fr: "le fils", es: "el hijo" },
        { fr: "la fille", es: "la hija" },
        { fr: "les grands-parents", es: "los abuelos" },
      ]},
    ],
  },
  {
    id: 10,
    title: "Le temps qui passe",
    subtitle: "Días, meses y estaciones",
    icon: "📅",
    vocab: [
      { fr: "lundi", es: "lunes", emoji: "📆" },
      { fr: "dimanche", es: "domingo", emoji: "📆" },
      { fr: "janvier", es: "enero", emoji: "❄️" },
      { fr: "juillet", es: "julio", emoji: "☀️" },
      { fr: "le printemps", es: "la primavera", emoji: "🌸" },
      { fr: "l'été", es: "el verano", emoji: "🏖️" },
      { fr: "l'automne", es: "el otoño", emoji: "🍂" },
      { fr: "l'hiver", es: "el invierno", emoji: "❄️" },
    ],
    grammar: {
      title: "Días, meses y estaciones no llevan mayúscula",
      text: "A diferencia del inglés, en francés (como en español) los días de la semana y los meses se escriben con minúscula: lundi, mardi... janvier, février... Para decir 'en' + estación se usa 'en' (en été, en automne, en hiver) pero con primavera es 'au printemps'.",
      examples: [
        { fr: "Mon anniversaire est en juillet.", es: "Mi cumpleaños es en julio." },
        { fr: "J'adore l'été !", es: "¡Me encanta el verano!" },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cuál es el primer día de la semana en el calendario francés?", options: ["dimanche", "lundi", "samedi", "mardi"], answer: 1 },
      { type: "fill", question: "En hiver il neige, en ___ il fait chaud. (verano)", answer: "été", hint: "La estación de la playa" },
      { type: "match", pairs: [
        { fr: "le printemps", es: "la primavera" },
        { fr: "l'automne", es: "el otoño" },
        { fr: "janvier", es: "enero" },
        { fr: "dimanche", es: "domingo" },
      ]},
    ],
  },
  {
    id: 11,
    title: "Quelle heure est-il ?",
    subtitle: "La hora",
    icon: "⏰",
    vocab: [
      { fr: "Quelle heure est-il ?", es: "¿Qué hora es?", emoji: "⏰" },
      { fr: "Il est une heure.", es: "Es la una.", emoji: "🕐" },
      { fr: "Il est midi.", es: "Es mediodía.", emoji: "🕛" },
      { fr: "Il est minuit.", es: "Es medianoche.", emoji: "🌙" },
      { fr: "et demie", es: "y media", emoji: "🕠" },
      { fr: "et quart", es: "y cuarto", emoji: "🕜" },
      { fr: "moins le quart", es: "menos cuarto", emoji: "🕞" },
    ],
    grammar: {
      title: "Decir la hora",
      text: "Para preguntar la hora: 'Quelle heure est-il ?'. Para responder usa 'Il est...' + la hora: 'Il est trois heures' (Son las tres). 'Une heure' es especial porque 'heure' es femenino, así que no lleva 's'. Mediodía y medianoche son 'midi' y 'minuit', sin artículo.",
      examples: [
        { fr: "Il est huit heures et demie.", es: "Son las ocho y media." },
        { fr: "Il est midi.", es: "Es mediodía." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se pregunta la hora en francés?", options: ["Quel jour est-il ?", "Quelle heure est-il ?", "Quel âge as-tu ?", "Où est-il ?"], answer: 1 },
      { type: "fill", question: "Il est ___. (mediodía)", answer: "midi", hint: "Las 12:00 del día" },
      { type: "match", pairs: [
        { fr: "et demie", es: "y media" },
        { fr: "et quart", es: "y cuarto" },
        { fr: "minuit", es: "medianoche" },
        { fr: "midi", es: "mediodía" },
      ]},
    ],
  },
  {
    id: 12,
    title: "Quel temps fait-il ?",
    subtitle: "El clima",
    icon: "🌦️",
    vocab: [
      { fr: "Il fait beau.", es: "Hace buen tiempo.", emoji: "☀️" },
      { fr: "Il fait chaud.", es: "Hace calor.", emoji: "🥵" },
      { fr: "Il fait froid.", es: "Hace frío.", emoji: "🥶" },
      { fr: "Il pleut.", es: "Llueve.", emoji: "🌧️" },
      { fr: "Il neige.", es: "Nieva.", emoji: "❄️" },
      { fr: "Il y a du vent.", es: "Hay viento.", emoji: "💨" },
      { fr: "un nuage", es: "una nube", emoji: "☁️" },
    ],
    grammar: {
      title: "Expresiones con 'il fait' e 'il y a'",
      text: "Para hablar del clima, el francés usa mucho la estructura impersonal 'Il fait...' (literalmente 'hace...'): 'Il fait beau/chaud/froid'. Para lluvia y nieve se usan verbos propios: 'il pleut' (llueve), 'il neige' (nieva). Para el viento: 'il y a du vent'.",
      examples: [
        { fr: "Aujourd'hui il fait beau et il y a du soleil.", es: "Hoy hace buen tiempo y hay sol." },
        { fr: "Demain il va pleuvoir.", es: "Mañana va a llover." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'llueve' en francés?", options: ["Il neige", "Il pleut", "Il fait froid", "Il y a du vent"], answer: 1 },
      { type: "fill", question: "Il fait ___ en été. (calor)", answer: "chaud", hint: "Lo contrario de 'froid'" },
      { type: "match", pairs: [
        { fr: "Il fait froid", es: "Hace frío" },
        { fr: "Il neige", es: "Nieva" },
        { fr: "Il y a du vent", es: "Hay viento" },
        { fr: "Il fait beau", es: "Hace buen tiempo" },
      ]},
    ],
  },
  {
    id: 13,
    title: "Au restaurant",
    subtitle: "La comida y las bebidas",
    icon: "🥐",
    vocab: [
      { fr: "le pain", es: "el pan", emoji: "🍞" },
      { fr: "le fromage", es: "el queso", emoji: "🧀" },
      { fr: "l'eau", es: "el agua", emoji: "💧" },
      { fr: "le café", es: "el café", emoji: "☕" },
      { fr: "la viande", es: "la carne", emoji: "🍖" },
      { fr: "les légumes", es: "las verduras", emoji: "🥦" },
      { fr: "un croissant", es: "un croissant", emoji: "🥐" },
      { fr: "l'addition", es: "la cuenta", emoji: "🧾" },
    ],
    grammar: {
      title: "Pedir comida y el artículo partitivo",
      text: "Para decir 'algo de' comida se usa el artículo partitivo: 'du' (masc.), 'de la' (fem.), 'de l'' (vocal): 'Je voudrais du pain' (Quisiera pan), 'de la viande' (carne). Para pedir cortésmente usa 'Je voudrais...' (Quisiera...).",
      examples: [
        { fr: "Je voudrais un café, s'il vous plaît.", es: "Quisiera un café, por favor." },
        { fr: "L'addition, s'il vous plaît.", es: "La cuenta, por favor." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo pides la cuenta en un restaurante francés?", options: ["Le menu, s'il vous plaît", "L'addition, s'il vous plaît", "Le pain, s'il vous plaît", "Bonsoir"], answer: 1 },
      { type: "fill", question: "Je voudrais ___ pain. (partitivo masculino: 'un poco de')", answer: "du", hint: "Artículo partitivo masculino" },
      { type: "match", pairs: [
        { fr: "le fromage", es: "el queso" },
        { fr: "l'eau", es: "el agua" },
        { fr: "les légumes", es: "las verduras" },
        { fr: "un croissant", es: "un croissant" },
      ]},
    ],
  },
  {
    id: 14,
    title: "Verbes en -ER",
    subtitle: "Verbos regulares terminados en -ER",
    icon: "⚙️",
    vocab: [
      { fr: "parler", es: "hablar", emoji: "💬" },
      { fr: "aimer", es: "gustar/amar", emoji: "❤️" },
      { fr: "habiter", es: "vivir/habitar", emoji: "🏠" },
      { fr: "manger", es: "comer", emoji: "🍽️" },
      { fr: "regarder", es: "mirar/ver", emoji: "👀" },
      { fr: "travailler", es: "trabajar", emoji: "💼" },
    ],
    grammar: {
      title: "Conjugar verbos -ER",
      text: "La mayoría de verbos franceses terminan en '-ER' y se conjugan igual: quita '-er' y añade la terminación: je -e, tu -es, il/elle -e, nous -ons, vous -ez, ils/elles -ent. Ejemplo con 'parler': je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent.",
      examples: [
        { fr: "J'habite à Paris.", es: "Vivo en París." },
        { fr: "Nous parlons français.", es: "Nosotros hablamos francés." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se conjuga 'aimer' con 'nous'?", options: ["aimons", "aimez", "aiment", "aime"], answer: 0 },
      { type: "fill", question: "Tu ___ le français. (hablas)", answer: "parles", hint: "Segunda persona singular de 'parler'" },
      { type: "match", pairs: [
        { fr: "je mange", es: "yo como" },
        { fr: "ils regardent", es: "ellos miran" },
        { fr: "elle travaille", es: "ella trabaja" },
        { fr: "vous habitez", es: "ustedes viven" },
      ]},
    ],
  },
  {
    id: 15,
    title: "Les questions",
    subtitle: "Preguntas básicas: qui, quoi, où, quand...",
    icon: "❓",
    vocab: [
      { fr: "Qui ?", es: "¿Quién?", emoji: "🙋" },
      { fr: "Quoi ?", es: "¿Qué?", emoji: "❓" },
      { fr: "Où ?", es: "¿Dónde?", emoji: "📍" },
      { fr: "Quand ?", es: "¿Cuándo?", emoji: "🕐" },
      { fr: "Comment ?", es: "¿Cómo?", emoji: "🤔" },
      { fr: "Pourquoi ?", es: "¿Por qué?", emoji: "💭" },
      { fr: "Combien ?", es: "¿Cuánto?", emoji: "🔢" },
    ],
    grammar: {
      title: "Formar preguntas",
      text: "La forma más sencilla de preguntar es poner la palabra interrogativa al inicio o final de la frase, o simplemente subir la entonación: 'Tu habites où ?' / 'Où habites-tu ?' (¿Dónde vives?). 'Pourquoi' se responde con 'parce que' (porque).",
      examples: [
        { fr: "Comment tu t'appelles ?", es: "¿Cómo te llamas?" },
        { fr: "Pourquoi tu apprends le français ? — Parce que j'aime la culture.", es: "¿Por qué aprendes francés? — Porque me gusta la cultura." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Qué palabra usarías para preguntar '¿Dónde?'", options: ["Quand", "Où", "Qui", "Combien"], answer: 1 },
      { type: "fill", question: "___ est-ce que tu apprends le français ? (¿Por qué?)", answer: "Pourquoi", hint: "Se responde con 'parce que'" },
      { type: "match", pairs: [
        { fr: "Qui ?", es: "¿Quién?" },
        { fr: "Quand ?", es: "¿Cuándo?" },
        { fr: "Combien ?", es: "¿Cuánto?" },
        { fr: "Comment ?", es: "¿Cómo?" },
      ]},
    ],
  },
  {
    id: 16,
    title: "Révision finale",
    subtitle: "Posesivos, negación y repaso general de A1",
    icon: "🏆",
    vocab: [
      { fr: "mon / ma / mes", es: "mi / mis", emoji: "👉" },
      { fr: "ton / ta / tes", es: "tu / tus", emoji: "👉" },
      { fr: "son / sa / ses", es: "su / sus", emoji: "👉" },
      { fr: "ne ... pas", es: "no (negación)", emoji: "🚫" },
      { fr: "je ne sais pas", es: "no lo sé", emoji: "🤷" },
      { fr: "félicitations !", es: "¡felicidades!", emoji: "🎉" },
    ],
    grammar: {
      title: "Adjetivos posesivos y la negación",
      text: "Los posesivos concuerdan con el sustantivo que sigue (no con quién posee): 'son père' puede ser 'su padre' (de él o de ella). Para negar, el francés 'envuelve' el verbo con 'ne ... pas': 'Je ne parle pas anglais' (No hablo inglés). ¡Con esto ya tienes las bases del nivel A1!",
      examples: [
        { fr: "Elle n'aime pas le café.", es: "A ella no le gusta el café." },
        { fr: "Ce n'est pas mon sac, c'est son sac.", es: "No es mi bolso, es su bolso." },
      ],
    },
    exercises: [
      { type: "mcq", question: "¿Cómo se dice 'No hablo francés' correctamente?", options: ["Je parle ne français pas", "Je ne parle pas français", "Ne je parle pas français", "Je pas parle ne français"], answer: 1 },
      { type: "fill", question: "Ce n'est ___ mon livre. (negación: no)", answer: "pas", hint: "Segunda parte de 'ne...pas'" },
      { type: "match", pairs: [
        { fr: "mon", es: "mi (masc.)" },
        { fr: "ta", es: "tu (fem.)" },
        { fr: "ses", es: "sus" },
        { fr: "ne...pas", es: "no" },
      ]},
    ],
  },
];

/* ============================================================
   Insignias / logros (independientes de las lecciones)
   ============================================================ */
const MILESTONE_BADGES = [
  { id: "first_step", icon: "🥐", title: "Primeros pasos", desc: "Completa tu primera lección", check: (p) => p.completedLessons.length >= 1 },
  { id: "numbers_master", icon: "🔢", title: "Maestro de los números", desc: "Completa las lecciones de números", check: (p) => p.completedLessons.includes(2) && p.completedLessons.includes(3) },
  { id: "halfway", icon: "🗼", title: "A mitad de camino", desc: "Completa 8 lecciones", check: (p) => p.completedLessons.length >= 8 },
  { id: "perfectionist", icon: "⭐", title: "Perfeccionista", desc: "Termina una lección sin errores", check: (p) => p.perfectLessons.length >= 1 },
  { id: "streak_3", icon: "🔥", title: "Constancia", desc: "3 días seguidos estudiando", check: (p) => p.streak >= 3 },
  { id: "streak_7", icon: "🔥🔥", title: "Racha de fuego", desc: "7 días seguidos estudiando", check: (p) => p.streak >= 7 },
  { id: "a1_complete", icon: "🏆", title: "¡Nivel A1 completado!", desc: "Termina las 16 lecciones", check: (p) => p.completedLessons.length >= LESSONS.length },
];
